// The content of this file is generated by 'scanner/main.go'.
// Do not modify it manually.
// Manual changes may cause issues with the program's operation.
// If modifications are needed, please do so through the program's logic.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq)]
pub enum MeshGatewayMode {
    /// MeshGatewayModeDefault represents no specific mode and should
    /// be used to indicate that a different layer of the configuration
    /// chain should take precedence
    #[serde(rename = "")]
    Default,

    /// MeshGatewayModeNone represents that the Upstream Connect connections
    /// should be direct and not flow through a mesh gateway.
    #[serde(rename = "none")]
    None,

    /// MeshGatewayModeLocal represents that the Upstream Connect connections
    /// should be made to a mesh gateway in the local datacenter.
    #[serde(rename = "local")]
    Local,

    /// MeshGatewayModeRemote represents that the Upstream Connect connections
    /// should be made to a mesh gateway in a remote datacenter.
    #[serde(rename = "remote")]
    Remote,
}

impl Default for MeshGatewayMode {
    fn default() -> Self {
        Self::Default
    }
}

impl ::core::fmt::Display for MeshGatewayMode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Default => write!(f, ""),
            Self::None => write!(f, "none"),
            Self::Local => write!(f, "local"),
            Self::Remote => write!(f, "remote"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq)]
pub enum ProxyMode {
    /// ProxyModeDefault represents no specific mode and should
    /// be used to indicate that a different layer of the configuration
    /// chain should take precedence
    #[serde(rename = "")]
    Default,

    /// ProxyModeTransparent represents that inbound and outbound application
    /// traffic is being captured and redirected through the proxy.
    #[serde(rename = "transparent")]
    Transparent,

    /// ProxyModeDirect represents that the proxy's listeners must be dialed directly
    /// by the local application and other proxies.
    #[serde(rename = "direct")]
    Direct,
}

impl Default for ProxyMode {
    fn default() -> Self {
        Self::Default
    }
}

impl ::core::fmt::Display for ProxyMode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Default => write!(f, ""),
            Self::Transparent => write!(f, "transparent"),
            Self::Direct => write!(f, "direct"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq)]
pub enum LogSinkType {
    #[serde(rename = "")]
    Default,
    #[serde(rename = "file")]
    File,
    #[serde(rename = "stderr")]
    StdErr,
    #[serde(rename = "stdout")]
    StdOut,
}

impl Default for LogSinkType {
    fn default() -> Self {
        Self::Default
    }
}

impl ::core::fmt::Display for LogSinkType {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Default => write!(f, ""),
            Self::File => write!(f, "file"),
            Self::StdErr => write!(f, "stderr"),
            Self::StdOut => write!(f, "stdout"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq)]
pub enum Health {
    /// HealthAny is special, and is used as a wild card,
    /// not as a specific state.
    #[serde(rename = "any")]
    Any,
    #[serde(rename = "passing")]
    Passing,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "critical")]
    Critical,
    #[serde(rename = "maintenance")]
    Maintenance,
}

impl Default for Health {
    fn default() -> Self {
        Self::Any
    }
}

impl ::core::fmt::Display for Health {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Any => write!(f, "any"),
            Self::Passing => write!(f, "passing"),
            Self::Warning => write!(f, "warning"),
            Self::Critical => write!(f, "critical"),
            Self::Maintenance => write!(f, "maintenance"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq)]
pub enum MutualTLSMode {
    #[serde(rename = "")]
    Default,
    #[serde(rename = "strict")]
    Strict,
    #[serde(rename = "permissive")]
    Permissive,
}

impl Default for MutualTLSMode {
    fn default() -> Self {
        Self::Default
    }
}

impl ::core::fmt::Display for MutualTLSMode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Default => write!(f, ""),
            Self::Strict => write!(f, "strict"),
            Self::Permissive => write!(f, "permissive"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq)]
pub enum UpstreamDestType {
    #[serde(rename = "")]
    None,
    #[serde(rename = "service")]
    Service,
    #[serde(rename = "prepared_query")]
    PreparedQuery,
}

impl Default for UpstreamDestType {
    fn default() -> Self {
        Self::None
    }
}

impl ::core::fmt::Display for UpstreamDestType {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::None => write!(f, ""),
            Self::Service => write!(f, "service"),
            Self::PreparedQuery => write!(f, "prepared_query"),
        }
    }
}
