// The content of this file is generated by 'scanner/main.go'.
// Do not modify it manually.
// Manual changes may cause issues with the program's operation.
// If modifications are needed, please do so through the program's logic.

use base64::{engine::general_purpose::STANDARD, Engine as _};
use serde::{Deserialize, Serialize};

#[derive(Debug, Copy, Clone, Serialize, Deserialize, Eq, PartialEq)]
pub enum MeshGatewayMode {
    /// MeshGatewayModeDefault represents no specific mode and should
    /// be used to indicate that a different layer of the configuration
    /// chain should take precedence
    #[serde(rename = "")]
    Default,

    /// MeshGatewayModeNone represents that the Upstream Connect connections
    /// should be direct and not flow through a mesh gateway.
    #[serde(rename = "none")]
    None,

    /// MeshGatewayModeLocal represents that the Upstream Connect connections
    /// should be made to a mesh gateway in the local datacenter.
    #[serde(rename = "local")]
    Local,

    /// MeshGatewayModeRemote represents that the Upstream Connect connections
    /// should be made to a mesh gateway in a remote datacenter.
    #[serde(rename = "remote")]
    Remote,
}

impl Default for MeshGatewayMode {
    fn default() -> Self {
        Self::Default
    }
}

impl ::core::fmt::Display for MeshGatewayMode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Default => write!(f, ""),
            Self::None => write!(f, "none"),
            Self::Local => write!(f, "local"),
            Self::Remote => write!(f, "remote"),
        }
    }
}

// TODO 不清楚为何会返回 “Default”，但又不在定义中，所以暂时用字符串代替这个定义
// #[derive(Debug, Copy, Clone, Serialize, Deserialize, Eq, PartialEq)]
// pub enum ProxyMode {
//     /// ProxyModeDefault represents no specific mode and should
//     /// be used to indicate that a different layer of the configuration
//     /// chain should take precedence
//     #[serde(rename = "")]
//     Default,

//     /// ProxyModeTransparent represents that inbound and outbound application
//     /// traffic is being captured and redirected through the proxy.
//     #[serde(rename = "transparent")]
//     Transparent,

//     /// ProxyModeDirect represents that the proxy's listeners must be dialed directly
//     /// by the local application and other proxies.
//     #[serde(rename = "direct")]
//     Direct,
// }

// impl Default for ProxyMode {
//     fn default() -> Self {
//         Self::Default
//     }
// }

// impl ::core::fmt::Display for ProxyMode {
//     fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
//         match self {
//             Self::Default => write!(f, ""),
//             Self::Transparent => write!(f, "transparent"),
//             Self::Direct => write!(f, "direct"),
//         }
//     }
// }

#[derive(Debug, Copy, Clone, Serialize, Deserialize, Eq, PartialEq)]
pub enum LogSinkType {
    #[serde(rename = "")]
    Default,
    #[serde(rename = "file")]
    File,
    #[serde(rename = "stderr")]
    StdErr,
    #[serde(rename = "stdout")]
    StdOut,
}

impl Default for LogSinkType {
    fn default() -> Self {
        Self::Default
    }
}

impl ::core::fmt::Display for LogSinkType {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Default => write!(f, ""),
            Self::File => write!(f, "file"),
            Self::StdErr => write!(f, "stderr"),
            Self::StdOut => write!(f, "stdout"),
        }
    }
}

#[derive(Debug, Copy, Clone, Serialize, Deserialize, Eq, PartialEq)]
pub enum Health {
    /// HealthAny is special, and is used as a wild card,
    /// not as a specific state.
    #[serde(rename = "any")]
    Any,
    #[serde(rename = "passing")]
    Passing,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "critical")]
    Critical,
    #[serde(rename = "maintenance")]
    Maintenance,
}

impl Default for Health {
    fn default() -> Self {
        Self::Any
    }
}

impl From<&str> for Health {
    fn from(s: &str) -> Self {
        match s {
            _ => Self::Any,
            "passing" => Self::Passing,
            "warning" => Self::Warning,
            "critical" => Self::Critical,
            "maintenance" => Self::Maintenance,
        }
    }
}

impl ::core::fmt::Display for Health {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Any => write!(f, "any"),
            Self::Passing => write!(f, "passing"),
            Self::Warning => write!(f, "warning"),
            Self::Critical => write!(f, "critical"),
            Self::Maintenance => write!(f, "maintenance"),
        }
    }
}

#[derive(Debug, Copy, Clone, Serialize, Deserialize, Eq, PartialEq)]
pub enum GatewayServiceKind {
    #[serde(rename = "")]
    Unknown,
    #[serde(rename = "destination")]
    Destination,
    #[serde(rename = "service")]
    Service,
}

impl Default for GatewayServiceKind {
    fn default() -> Self {
        Self::Unknown
    }
}

impl ::core::fmt::Display for GatewayServiceKind {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Unknown => write!(f, ""),
            Self::Destination => write!(f, "destination"),
            Self::Service => write!(f, "service"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Base64Payload(pub(crate) String);

impl Base64Payload {
    pub fn to_vec(&self) -> Vec<u8> {
        STANDARD.decode(&self.0).unwrap()
    }
}
