package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

var rustFile = strings.Builder{}

func init() {
	rustFile.WriteString("// Generated by 'scanner/main.go'.\n\n")
	rustFile.WriteString("use serde::{Serialize, Deserialize};\n\n")
}

func main() {
	workspace := filepath.Dir(getGoEnv("GOMOD"))
	consulPath := filepath.Join(workspace, "..", "consul")
	outputFilename := filepath.Join(workspace, "..", "src/structs.rs")
	agentPath := filepath.Join(consulPath, "agent")
	structsPath := filepath.Join(agentPath, "structs")

	println("workspace: ", workspace)
	println("consulPath: ", consulPath)
	println("agentPath: ", agentPath)
	println("structsPath: ", structsPath)

	walkAllFiles(structsPath)
	// extractFromPath(filepath.Join(structsPath, "structs.go"))
	// parseGoFile(filepath.Join(structsPath, "structs.go"))

	// println("Done.")
	// println(rustFile.String())

	// 写入文件
	err := os.WriteFile(outputFilename, []byte(rustFile.String()), os.ModePerm)
	if err != nil {
		fmt.Println("Error writing file:", err)
		os.Exit(1)
	}
}

func parseGoFile(path string) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, path, nil, parser.ParseComments|parser.AllErrors)
	if err != nil {
		fmt.Println("Error parsing file:", err)
		os.Exit(1)
	}

	ast.Inspect(node, func(n ast.Node) bool {
		// 检查是否为结构体类型声明
		gd, ok := n.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			return true
		}

		structComment := strings.TrimSpace(gd.Doc.Text())
		structComment = strings.ReplaceAll(structComment, "\n", "\n/// ")

		for _, spec := range gd.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			// 检查是否为结构体
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if structSkip(typeSpec.Name.Name) {
				continue
			}

			if structComment != "" {
				rustFile.WriteString(fmt.Sprintf("/// %s\n", structComment))
			}

			// 输出结构体的名称和注释
			fmt.Printf("Struct Name: %s\n", typeSpec.Name.Name)
			rustFile.WriteString(structDerive(typeSpec.Name.Name))
			rustFile.WriteString(fmt.Sprintf("pub struct %s {\n", typeSpec.Name.Name))

			// 遍历结构体的字段
			for _, field := range structType.Fields.List {
				fieldName := ""
				fieldType := ""
				fieldRustType := ""
				fieldTag := ""
				fieldComment := ""
				fieldVec := 0
				fieldOptional := false

				// 提取字段注释
				if field.Doc != nil {
					fieldComment = strings.TrimSpace(field.Doc.Text())
					fieldComment = strings.ReplaceAll(fieldComment, "\n", "\n    /// ")
				}

				// 提取字段标签
				if field.Tag != nil {
					fieldTag = field.Tag.Value

					if strings.Contains(fieldTag, "omitempty") {
						fieldOptional = true
					}
				}

				// 提取字段类型
				if field.Type != nil {
					se := unwrapSelectorExpr(field.Type)
					if se != nil {
						if isDuration(se) {
							fieldType = "time.Duration"
							break
						} else if isTime(se) {
							fieldType = "time.Time"
							break
						} else {
							fieldType = se.Sel.Name
							// if e, ok := field.Type.(*ast.Ident); ok {
							// 	// fmt.Printf("B %s\n", e.Name)
							// 	fieldType = e.Name
							// }
							// println("\tNot support this type: ", fieldType)
						}
					} else {
						opt, vec, val := parseType(field.Type)
						if opt {
							fieldOptional = true
						}
						if vec > 0 {
							fieldVec += vec
						}
						fieldType = val
						// fieldType = "*************************"

						// fmt.Printf("%v\n============================\n", fieldType)
						// fieldType = strings.Split(fieldType, " ")[0]
					}

					// for {
					// 	if l, found := strings.CutPrefix(fieldType, "[]"); found {
					// 		fieldType = l
					// 		fieldVec += 1
					// 		fieldType = strings.TrimPrefix(fieldType, "[]")
					// 		continue
					// 	}

					// 	break
					// }

					fieldRustType = toRustType(fieldType)
				}

				// 提取字段名称
				if field.Names != nil {
					fieldName = strings.TrimSpace(field.Names[0].Name)
				} else {
					fieldName = fieldType
				}

				if fieldComment == "" {
					// rustFile.WriteString(fmt.Sprintf("  /// %s\n", fieldName))
				} else {
					rustFile.WriteString(fmt.Sprintf("    /// %s\n", fieldComment))
				}

				if fieldType == "QueryMeta" || fieldType == "QueryOptions" || fieldType == "WriteRequest" {
					fieldOptional = true
				}

				if fieldType == "EnterpriseMeta" {
					fieldOptional = true
					rustFile.WriteString("    #[cfg(feature = \"enterprise\")]\n")
				}

				rustFile.WriteString(fmt.Sprintf("    #[serde(rename = \"%s\")]\n", fieldName))

				typename := fieldRustType
				for i := 0; i < fieldVec; i++ {
					typename = fmt.Sprintf("Vec<%s>", typename)
				}
				if fieldOptional {
					rustFile.WriteString("    #[serde(skip_serializing_if = \"Option::is_none\")]\n")
					typename = fmt.Sprintf("Option<%s>", typename)
				}
				name := toSnake(fieldName)
				if name == "type" {
					name = "r#type"
				} else if name == "match" {
					name = "r#match"
				} else if name == "override" {
					name = "r#override"
				}
				rustFile.WriteString(fmt.Sprintf("    pub %s: %s,\n\n", name, typename))
			}

			// end of struct
			rustFile.WriteString("}\n\n")

			// struct extra
			extraBody := structExtra(typeSpec.Name.Name)
			if extraBody != "" {
				rustFile.WriteString(extraBody)
			}
		}
		return true
	})
}

func parseType(t ast.Expr) (bool, int, string) {
	// 识别指针类型
	if e, ok := t.(*ast.StarExpr); ok {
		// fmt.Printf("\t%s\t\tA %v\n", fieldName, e)
		return true, 0, e.X.(*ast.Ident).Name
	}

	// if e, ok := field.Type.(*ast.FieldList); ok {
	// 	fmt.Printf("\t%s\t\tA %s\n", fieldName, e)
	// }
	if e, ok := t.(*ast.Ident); ok {
		// fmt.Printf("\t%s\t\tB %s\n", fieldName, e.Name)
		return false, 0, e.Name
	}

	if e, ok := t.(*ast.ArrayType); ok {
		// fmt.Printf("\t%s\t\tD %s\n", fieldName, e)
		// if f, ok := e.Elt.(*ast.StarExpr); ok {
		// 	return false, 1, f.X.(*ast.Ident).Name
		// } else if g, ok := e.Elt.(*ast.Ident); ok {
		// 	return false, 1, g.Name
		// 	// fieldType = toRustType(fmt.Sprintf("%s", e.Elt.(*ast.Ident).Name))
		// }
		return parseType(e.Elt)
	}
	if e, ok := t.(*ast.MapType); ok {
		// fmt.Printf("\t%s\t\tC key=%s val=%s\n", fieldName, e.Key, e.Value)
		opt, vec, val := parseType(e.Value)
		return opt, vec, fmt.Sprintf(
			"::std::collections::HashMap<%s, %s>",
			toRustType(fmt.Sprintf("%s", e.Key)),
			toRustType(val),
		)
	}
	return false, 0, ""
}

// 哪些 struct 需要跳过
func structSkip(name string) bool {
	// 检查首字母是否为小写
	if name[0] >= 'a' && name[0] <= 'z' {
		return true
	}

	if strings.HasPrefix(name, "Txn") {
		return true
	}

	switch name {
	default:
		return true
	case
		"HealthCheck",
		"HealthCheckDefinition",
		"CheckDefinition",
		"RaftIndex",
		"NodeService",
		"EnterpriseMeta",
		"ServiceKind",
		"ServiceAddress",
		"Weights",
		"Locality",
		"ConnectProxyConfig",
		"ServiceConnect",
		"WriteRequest",
		"QueryOptions":
		return false
	}
}

// 指定 struct derive
func structDerive(name string) string {
	switch name {
	default:
		return "#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n"
	}
}

// struct 的自定义扩展内容
func structExtra(name string) string {
	switch name {
	default:
		return ""
	case "ACLServiceIdentity":
		return "pub type ACLServiceIdentities = Vec<ACLServiceIdentity>;\n\n"
	case "ACLNodeIdentity":
		return "pub type ACLNodeIdentities = Vec<ACLNodeIdentity>;\n\n"
	case "ACLTemplatedPolicy":
		return "pub type ACLTemplatedPolicies = Vec<ACLTemplatedPolicy>;\n\n"
	case "ACLTokenListStub":
		return "pub type ACLTokenListStubs = Vec<ACLTokenListStub>;\n\n"
	case "ACLPolicyListStub":
		return "pub type ACLPolicyListStubs = Vec<ACLPolicyListStub>;\n\n"
	case "ACLAuthMethod":
		return "pub type ACLAuthMethods = Vec<ACLAuthMethod>;\n\n"
	case "ACLAuthMethodListStub":
		return "pub type ACLAuthMethodListStubs = Vec<ACLAuthMethodListStub>;\n\n"
	case "ACLBindingRule":
		return "pub type ACLBindingRules = Vec<ACLBindingRule>;\n\n"
	case "ACLRole":
		return "pub type ACLRoles = Vec<ACLRole>;\n\n"
	case "ACLToken":
		return "pub type ACLTokens = Vec<ACLToken>;\n\n"
	case "ACLPolicy":
		return "pub type ACLPolicies = Vec<ACLPolicy>;\n\n"
	}
}

func toRustType(name string) string {
	switch name {
	default:
		return name
	case "time.Duration":
		return "Duration"
	case "time.Time":
		return "DateTime"
	case "string", "CheckID", "ServiceKind":
		return "String"
	case "int":
		return "isize"
	case "int8":
		return "i8"
	case "int16":
		return "i16"
	case "int32":
		return "i32"
	case "int64":
		return "i64"
	case "uint":
		return "usize"
	case "uint8", "byte":
		return "u8"
	case "uint16":
		return "u16"
	case "uint32":
		return "u32"
	case "uint64":
		return "u64"
	case "bool":
		return "bool"
	}
}

// func extractFromPath(path string) {
// buf, err := os.ReadFile(path)
// if err != nil {
// 	return
// }

// structs, err := extractStructs(buf)
// if err != nil {
// 	println(err)
// 	return
// }

// for _, item := range structs {
// rustFile += item.String()
// }
// }

func walkAllFiles(path string) {
	if err := filepath.Walk(path, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if filepath.Ext(path) != ".go" {
			return nil
		}
		// Don't extract from test files.
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}

		parseGoFile(path)

		return nil
	}); err != nil {
		return
	}
}

// func extractStructs(buf []byte) ([]*parsedStruct, error) {
// 	fset := token.NewFileSet()
// 	file, err := parser.ParseFile(fset, "", buf, parser.ParseComments)
// 	if err != nil {
// 		return nil, err
// 	}
// 	extractor := &extractor{buffer: buf, structs: []*parsedStruct{}}
// 	ast.Walk(extractor, file)
// 	return extractor.structs, nil
// }

var goEnvCache = ""

func getGoEnv(key string) string {
	if goEnvCache != "" {
		return goEnvCache
	}
	out, err := exec.Command("go", "env", key).Output()
	if err != nil {
		panic(err.Error())
	}
	goEnvCache = string(out)
	return string(out)
}

var matchNonAlphaNumeric = regexp.MustCompile(`[^a-zA-Z0-9]+`)
var matchFirstCap = regexp.MustCompile("(.)([A-Z][a-z]+)")
var matchAllCap = regexp.MustCompile("([a-z0-9])([A-Z])")

func toSnake(camel string) string {
	camel = matchNonAlphaNumeric.ReplaceAllString(camel, "_")   //非常规字符转化为 _
	snake := matchFirstCap.ReplaceAllString(camel, "${1}_${2}") //拆分出连续大写
	snake = matchAllCap.ReplaceAllString(snake, "${1}_${2}")    //拆分单词
	return strings.ToLower(snake)                               //全部转小写
}

// here is the test
// func testToSnake(t *testing.T) {
// 	input := "MyLIFEIsAwesomE"
// 	want := "my_life_is_awesom_e"
// 	if got := toSnake(input); got != want {
// 		t.Errorf("ToSnake(%v) = %v, want %v", input, got, want)
// 	}
// }

func isTime(se *ast.SelectorExpr) bool {
	if se.Sel.Name != "Time" {
		return false
	}
	x, ok := se.X.(*ast.Ident)
	if !ok {
		return false
	}
	return x.Name == "time"
}

func isDuration(se *ast.SelectorExpr) bool {
	if se.Sel.Name != "Duration" {
		return false
	}
	x, ok := se.X.(*ast.Ident)
	if !ok {
		return false
	}
	return x.Name == "time"
}

func unwrapSelectorExpr(e ast.Expr) *ast.SelectorExpr {
	switch et := e.(type) {
	case *ast.SelectorExpr:
		return et
	case *ast.StarExpr:
		se, _ := et.X.(*ast.SelectorExpr)
		return se
	default:
		return nil
	}
}
