// The content of this file is generated by 'scanner/main.go'.
// Do not modify it manually.
// Manual changes may cause issues with the program's operation.
// If modifications are needed, please do so through the program's logic.

use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MeshGatewayMode {
    /// MeshGatewayModeDefault represents no specific mode and should
    /// be used to indicate that a different layer of the configuration
    /// chain should take precedence
    Default,

    /// MeshGatewayModeNone represents that the Upstream Connect connections
    /// should be direct and not flow through a mesh gateway.
    None,

    /// MeshGatewayModeLocal represents that the Upstream Connect connections
    /// should be made to a mesh gateway in the local datacenter.
    Local,

    /// MeshGatewayModeRemote represents that the Upstream Connect connections
    /// should be made to a mesh gateway in a remote datacenter.
    Remote,
}

impl Default for MeshGatewayMode {
    fn default() -> Self {
        Self::Default
    }
}

impl ::core::fmt::Display for MeshGatewayMode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Default => write!(f, ""),
            Self::None => write!(f, "none"),
            Self::Local => write!(f, "local"),
            Self::Remote => write!(f, "remote"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ProxyMode {
    /// ProxyModeDefault represents no specific mode and should
    /// be used to indicate that a different layer of the configuration
    /// chain should take precedence
    Default,

    /// ProxyModeTransparent represents that inbound and outbound application
    /// traffic is being captured and redirected through the proxy.
    Transparent,

    /// ProxyModeDirect represents that the proxy's listeners must be dialed directly
    /// by the local application and other proxies.
    Direct,
}

impl Default for ProxyMode {
    fn default() -> Self {
        Self::Default
    }
}

impl ::core::fmt::Display for ProxyMode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Default => write!(f, ""),
            Self::Transparent => write!(f, "transparent"),
            Self::Direct => write!(f, "direct"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum LogSinkType {
    Default,
    File,
    StdErr,
    StdOut,
}

impl Default for LogSinkType {
    fn default() -> Self {
        Self::Default
    }
}

impl ::core::fmt::Display for LogSinkType {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Default => write!(f, ""),
            Self::File => write!(f, "file"),
            Self::StdErr => write!(f, "stderr"),
            Self::StdOut => write!(f, "stdout"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MutualTLSMode {
    Default,
    Strict,
    Permissive,
}

impl Default for MutualTLSMode {
    fn default() -> Self {
        Self::Default
    }
}

impl ::core::fmt::Display for MutualTLSMode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match self {
            Self::Default => write!(f, ""),
            Self::Strict => write!(f, "strict"),
            Self::Permissive => write!(f, "permissive"),
        }
    }
}


/// CheckDefinition is used to JSON decode the Check definitions
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CheckDefinition {
    #[serde(rename = "ID")]
    pub id: String,

    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "Notes")]
    pub notes: String,

    #[serde(rename = "ServiceID")]
    pub service_id: String,

    #[serde(rename = "Token")]
    pub token: String,

    #[serde(rename = "Status")]
    pub status: String,

    /// Copied fields from CheckType without the fields
    /// already present in CheckDefinition:
    /// 
    ///   ID (CheckID), Name, Status, Notes
    #[serde(rename = "ScriptArgs")]
    pub script_args: String,

    #[serde(rename = "HTTP")]
    pub http: String,

    #[serde(rename = "H2PING")]
    pub h2_ping: String,

    #[serde(rename = "H2PingUseTLS")]
    pub h2_ping_use_tls: bool,

    #[serde(rename = "Header")]
    pub header: ::std::collections::HashMap<String, String>,

    #[serde(rename = "Method")]
    pub method: String,

    #[serde(rename = "Body")]
    pub body: String,

    #[serde(rename = "DisableRedirects")]
    pub disable_redirects: bool,

    #[serde(rename = "TCP")]
    pub tcp: String,

    #[serde(rename = "TCPUseTLS")]
    pub tcp_use_tls: bool,

    #[serde(rename = "UDP")]
    pub udp: String,

}

/// CheckType is used to create either the CheckMonitor or the CheckTTL.
/// The following types are supported: Script, HTTP, TCP, Docker, TTL, GRPC, Alias, H2PING. Script,
/// HTTP, Docker, TCP, GRPC, and H2PING all require Interval. Only one of the types may
/// to be provided: TTL or Script/Interval or HTTP/Interval or TCP/Interval or
/// Docker/Interval or GRPC/Interval or AliasService or H2PING/Interval.
/// Since types like CheckHTTP and CheckGRPC derive from CheckType, there are
/// helper conversion methods that do the reverse conversion. ie. checkHTTP.CheckType()
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CheckType {
    #[serde(rename = "CheckID")]
    pub check_id: String,

    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "Status")]
    pub status: String,

    #[serde(rename = "Notes")]
    pub notes: String,

    #[serde(rename = "ScriptArgs")]
    pub script_args: String,

    #[serde(rename = "HTTP")]
    pub http: String,

    #[serde(rename = "H2PING")]
    pub h2_ping: String,

    #[serde(rename = "H2PingUseTLS")]
    pub h2_ping_use_tls: bool,

    #[serde(rename = "Header")]
    pub header: ::std::collections::HashMap<String, String>,

    #[serde(rename = "Method")]
    pub method: String,

    #[serde(rename = "Body")]
    pub body: String,

    #[serde(rename = "DisableRedirects")]
    pub disable_redirects: bool,

    #[serde(rename = "TCP")]
    pub tcp: String,

    #[serde(rename = "TCPUseTLS")]
    pub tcp_use_tls: bool,

    #[serde(rename = "UDP")]
    pub udp: String,

}

pub type CheckTypes = Vec<CheckType>;

/// ConnectAuthorizeRequest is the structure of a request to authorize
/// a connection.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConnectAuthorizeRequest {
    /// Target is the name of the service that is being requested.
    #[serde(rename = "Target")]
    pub target: String,

    /// ClientCertURI is a unique identifier for the requesting client. This
    /// is currently the URI SAN from the TLS client certificate.
    /// 
    /// ClientCertSerial is a colon-hex-encoded of the serial number for
    /// the requesting client cert. This is used to check against revocation
    /// lists.
    #[serde(rename = "ClientCertURI")]
    pub client_cert_uri: String,

    #[serde(rename = "ClientCertSerial")]
    pub client_cert_serial: String,

}

/// MeshGatewayConfig controls how Mesh Gateways are configured and used
/// This is a struct to allow for future additions without having more free-hanging
/// configuration items all over the place
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MeshGatewayConfig {
    /// The Mesh Gateway routing mode
    #[serde(rename = "Mode")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<MeshGatewayMode>,

}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TransparentProxyConfig {
    /// The port of the listener where outbound application traffic is being redirected to.
    #[serde(rename = "OutboundListenerPort")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outbound_listener_port: Option<isize>,

    /// DialedDirectly indicates whether transparent proxies can dial this proxy instance directly.
    /// The discovery chain is not considered when dialing a service instance directly.
    /// This setting is useful when addressing stateful services, such as a database cluster with a leader node.
    #[serde(rename = "DialedDirectly")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dialed_directly: Option<bool>,

}

/// AccessLogsConfig contains the associated default settings for all Envoy instances within the datacenter or partition
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AccessLogsConfig {
    /// Enabled turns off all access logging
    #[serde(rename = "Enabled")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,

    /// DisableListenerLogs turns off just listener logs for connections rejected by Envoy because they don't
    /// have a matching listener filter.
    #[serde(rename = "DisableListenerLogs")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disable_listener_logs: Option<bool>,

    /// Type selects the output for logs: "file", "stderr". "stdout"
    #[serde(rename = "Type")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#type: Option<LogSinkType>,

    /// Path is the output file to write logs
    #[serde(rename = "Path")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    /// The presence of one format string or the other implies the access log string encoding.
    /// Defining Both is invalid.
    #[serde(rename = "JSONFormat")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub json_format: Option<String>,

    #[serde(rename = "TextFormat")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text_format: Option<String>,

}

/// ConnectProxyConfig describes the configuration needed for any proxy managed
/// or unmanaged. It describes a single logical service's listener and optionally
/// upstreams and sidecar-related config for a single instance. To describe a
/// centralized proxy that routed traffic for multiple services, a different one
/// of these would be needed for each, sharing the same LogicalProxyID.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConnectProxyConfig {
    /// EnvoyExtensions are the list of Envoy extensions configured for the local service.
    #[serde(rename = "EnvoyExtensions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub envoy_extensions: Option<EnvoyExtension>,

    /// DestinationServiceName is required and is the name of the service to accept
    /// traffic for.
    #[serde(rename = "DestinationServiceName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub destination_service_name: Option<String>,

    /// DestinationServiceID is optional and should only be specified for
    /// "side-car" style proxies where the proxy is in front of just a single
    /// instance of the service. It should be set to the service ID of the instance
    /// being represented which must be registered to the same agent. It's valid to
    /// provide a service ID that does not yet exist to avoid timing issues when
    /// bootstrapping a service with a proxy.
    #[serde(rename = "DestinationServiceID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub destination_service_id: Option<String>,

    /// LocalServiceAddress is the address of the local service instance. It is
    /// optional and should only be specified for "side-car" style proxies. It will
    /// default to 127.0.0.1 if the proxy is a "side-car" (DestinationServiceID is
    /// set) but otherwise will be ignored.
    #[serde(rename = "LocalServiceAddress")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub local_service_address: Option<String>,

    /// LocalServicePort is the port of the local service instance. It is optional
    /// and should only be specified for "side-car" style proxies. It will default
    /// to the registered port for the instance if the proxy is a "side-car"
    /// (DestinationServiceID is set) but otherwise will be ignored.
    #[serde(rename = "LocalServicePort")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub local_service_port: Option<isize>,

    /// LocalServiceSocketPath is the socket of the local service instance. It is optional
    /// and should only be specified for "side-car" style proxies.
    #[serde(rename = "LocalServiceSocketPath")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub local_service_socket_path: Option<String>,

    /// Mode represents how the proxy's inbound and upstream listeners are dialed.
    #[serde(rename = "Mode")]
    pub mode: ProxyMode,

    /// Upstreams describes any upstream dependencies the proxy instance should
    /// setup.
    #[serde(rename = "Upstreams")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub upstreams: Option<Upstreams>,

    /// MeshGateway defines the mesh gateway configuration for this upstream
    #[serde(rename = "MeshGateway")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mesh_gateway: Option<MeshGatewayConfig>,

    /// Expose defines whether checks or paths are exposed through the proxy
    #[serde(rename = "Expose")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expose: Option<ExposeConfig>,

    /// TransparentProxy defines configuration for when the proxy is in
    /// transparent mode.
    #[serde(rename = "TransparentProxy")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transparent_proxy: Option<TransparentProxyConfig>,

    /// MutualTLSMode allows configuring the proxy to allow non-mTLS traffic.
    #[serde(rename = "MutualTLSMode")]
    pub mutual_tls_mode: MutualTLSMode,

    /// AccessLogs configures the output and format of Envoy access logs
    #[serde(rename = "AccessLogs")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub access_logs: Option<AccessLogsConfig>,

}

/// Upstream represents a single upstream dependency for a service or proxy. It
/// describes the mechanism used to discover instances to communicate with (the
/// Target) as well as any potential client configuration that may be useful such
/// as load balancer options, timeouts etc.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Upstream {
    /// Destination fields are the required ones for determining what this upstream
    /// points to. Depending on DestinationType some other fields below might
    /// further restrict the set of instances allowable.
    /// 
    /// DestinationType would be better as an int constant but even with custom
    /// JSON marshallers it causes havoc with all the mapstructure mangling we do
    /// on service definitions in various places.
    #[serde(rename = "DestinationType")]
    pub destination_type: String,

    #[serde(rename = "DestinationNamespace")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub destination_namespace: Option<String>,

    #[serde(rename = "DestinationPartition")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub destination_partition: Option<String>,

    #[serde(rename = "DestinationPeer")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub destination_peer: Option<String>,

    #[serde(rename = "DestinationName")]
    pub destination_name: String,

    /// Datacenter that the service discovery request should be run against. Note
    /// for prepared queries, the actual results might be from a different
    /// datacenter.
    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    /// LocalBindAddress is the ip address a side-car proxy should listen on for
    /// traffic destined for this upstream service. Default if empty is 127.0.0.1.
    #[serde(rename = "LocalBindAddress")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub local_bind_address: Option<String>,

    /// LocalBindPort is the ip address a side-car proxy should listen on for traffic
    /// destined for this upstream service. Required.
    #[serde(rename = "LocalBindPort")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub local_bind_port: Option<isize>,

    /// These are exclusive with LocalBindAddress/LocalBindPort
    #[serde(rename = "LocalBindSocketPath")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub local_bind_socket_path: Option<String>,

    /// This might be represented as an int, but because it's octal outputs can be a bit strange.
    #[serde(rename = "LocalBindSocketMode")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub local_bind_socket_mode: Option<String>,

    /// MeshGateway is the configuration for mesh gateway usage of this upstream
    #[serde(rename = "MeshGateway")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mesh_gateway: Option<MeshGatewayConfig>,

    /// IngressHosts are a list of hosts that should route to this upstream from an
    /// ingress gateway. This cannot and should not be set by a user, it is used
    /// internally to store the association of hosts to an upstream service.
    /// TODO(banks): we shouldn't need this any more now we pass through full
    /// listener config in the ingress snapshot.
    #[serde(rename = "IngressHosts")]
    pub ingress_hosts: String,

    /// CentrallyConfigured indicates whether the upstream was defined in a proxy
    /// instance registration or whether it was generated from a config entry.
    #[serde(rename = "CentrallyConfigured")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub centrally_configured: Option<bool>,

}

pub type Upstreams = Vec<Upstream>;

/// ExposeConfig describes HTTP paths to expose through Envoy outside of Connect.
/// Users can expose individual paths and/or all HTTP/GRPC paths for checks.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ExposeConfig {
    /// Checks defines whether paths associated with Consul checks will be exposed.
    /// This flag triggers exposing all HTTP and GRPC check paths registered for the service.
    #[serde(rename = "Checks")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checks: Option<bool>,

    /// Paths is the list of paths exposed through the proxy.
    #[serde(rename = "Paths")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paths: Option<ExposePath>,

}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ExposePath {
    /// ListenerPort defines the port of the proxy's listener for exposed paths.
    #[serde(rename = "ListenerPort")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub listener_port: Option<isize>,

    /// Path is the path to expose through the proxy, ie. "/metrics."
    #[serde(rename = "Path")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    /// LocalPathPort is the port that the service is listening on for the given path.
    #[serde(rename = "LocalPathPort")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub local_path_port: Option<isize>,

    /// Protocol describes the upstream's service protocol.
    /// Valid values are "http" and "http2", defaults to "http"
    #[serde(rename = "Protocol")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,

    /// ParsedFromCheck is set if this path was parsed from a registered check
    #[serde(rename = "ParsedFromCheck")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parsed_from_check: Option<bool>,

}

/// EnvoyExtension has configuration for an extension that patches Envoy resources.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EnvoyExtension {
    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "Required")]
    pub required: bool,

    #[serde(rename = "ConsulVersion")]
    pub consul_version: String,

    #[serde(rename = "EnvoyVersion")]
    pub envoy_version: String,

}

/// ServiceDefinition is used to JSON decode the Service definitions. For
/// documentation on specific fields see NodeService which is better documented.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ServiceDefinition {
    #[serde(rename = "Kind")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    #[serde(rename = "ID")]
    pub id: String,

    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "Tags")]
    pub tags: String,

    #[serde(rename = "Address")]
    pub address: String,

    #[serde(rename = "TaggedAddresses")]
    pub tagged_addresses: ::std::collections::HashMap<String, ServiceAddress>,

    #[serde(rename = "Meta")]
    pub meta: ::std::collections::HashMap<String, String>,

    #[serde(rename = "Port")]
    pub port: u16,

    #[serde(rename = "SocketPath")]
    pub socket_path: String,

    #[serde(rename = "Check")]
    pub check: CheckType,

    #[serde(rename = "Checks")]
    pub checks: CheckTypes,

    #[serde(rename = "Weights")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weights: Option<Weights>,

    #[serde(rename = "Token")]
    pub token: String,

    #[serde(rename = "EnableTagOverride")]
    pub enable_tag_override: bool,

    #[serde(rename = "Locality")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locality: Option<Locality>,

    /// Proxy is the configuration set for Kind = connect-proxy. It is mandatory in
    /// that case and an error to be set for any other kind. This config is part of
    /// a proxy service definition. ProxyConfig may be a more natural name here, but
    /// it's confusing for the UX because one of the fields in ConnectProxyConfig is
    /// also called just "Config"
    #[serde(rename = "Proxy")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy: Option<ConnectProxyConfig>,

    #[serde(rename = "Connect")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub connect: Option<Box<ServiceConnect>>,

}

/// RaftIndex is used to track the index used while creating
/// or modifying a given struct type.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RaftIndex {
    #[serde(rename = "CreateIndex")]
    pub create_index: u64,

    #[serde(rename = "ModifyIndex")]
    pub modify_index: u64,

}

/// QueryOptions is used to specify various flags for read queries
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct QueryOptions {
    /// Token is the ACL token ID. If not provided, the 'anonymous'
    /// token is assumed for backwards compatibility.
    #[serde(rename = "Token")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,

    /// If set, wait until query exceeds given index. Must be provided
    /// with MaxQueryTime.
    #[serde(rename = "MinQueryIndex")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_query_index: Option<u64>,

}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct WriteRequest {
    /// Token is the ACL token ID. If not provided, the 'anonymous'
    /// token is assumed for backwards compatibility.
    #[serde(rename = "Token")]
    pub token: String,

}

/// Weights represent the weight used by DNS for a given status
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Weights {
    #[serde(rename = "Passing")]
    pub passing: isize,

    #[serde(rename = "Warning")]
    pub warning: isize,

}

/// Type to hold a address and port of a service
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ServiceAddress {
    #[serde(rename = "Address")]
    pub address: String,

    #[serde(rename = "Port")]
    pub port: u16,

}

/// NodeService is a service provided by a node
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NodeService {
    /// Kind is the kind of service this is. Different kinds of services may
    /// have differing validation, DNS behavior, etc. An empty kind will default
    /// to the Default kind. See ServiceKind for the full list of kinds.
    #[serde(rename = "Kind")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    #[serde(rename = "ID")]
    pub id: String,

    #[serde(rename = "Service")]
    pub service: String,

    #[serde(rename = "Tags")]
    pub tags: String,

    #[serde(rename = "Address")]
    pub address: String,

    #[serde(rename = "TaggedAddresses")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tagged_addresses: Option<::std::collections::HashMap<String, ServiceAddress>>,

    #[serde(rename = "Meta")]
    pub meta: ::std::collections::HashMap<String, String>,

    #[serde(rename = "Port")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub port: Option<u16>,

    #[serde(rename = "SocketPath")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub socket_path: Option<String>,

    #[serde(rename = "Weights")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weights: Option<Weights>,

    #[serde(rename = "EnableTagOverride")]
    pub enable_tag_override: bool,

    #[serde(rename = "Locality")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locality: Option<Locality>,

    /// Proxy is the configuration set for Kind = connect-proxy. It is mandatory in
    /// that case and an error to be set for any other kind. This config is part of
    /// a proxy service definition. ProxyConfig may be a more natural name here, but
    /// it's confusing for the UX because one of the fields in ConnectProxyConfig is
    /// also called just "Config"
    #[serde(rename = "Proxy")]
    pub proxy: ConnectProxyConfig,

    /// Connect are the Connect settings for a service. This is purposely NOT
    /// a pointer so that we never have to nil-check this.
    #[serde(rename = "Connect")]
    pub connect: Box<ServiceConnect>,

    /// TODO: rename to reflect that this is used to express future intent to register.
    /// LocallyRegisteredAsSidecar is private as it is only used by a local agent
    /// state to track if the service was or will be registered from a nested sidecar_service
    /// block. We need to track that so we can know whether we need to deregister
    /// it automatically too if it's removed from the service definition or if the
    /// parent service is deregistered. Relying only on ID would cause us to
    /// deregister regular services if they happen to be registered using the same
    /// ID scheme as our sidecars do by default. We could use meta but that gets
    /// unpleasant because we can't use the consul- prefix from an agent (reserved
    /// for use internally but in practice that means within the state store or in
    /// responses only), and it leaks the detail publicly which people might rely
    /// on which is a bit unpleasant for something that is meant to be config-file
    /// syntax sugar. Note this is not translated to ServiceNode and friends and
    /// may not be set on a NodeService that isn't the one the agent registered and
    /// keeps in it's local state. We never want this rendered in JSON as it's
    /// internal only. Right now our agent endpoints return api structs which don't
    /// include it but this is a safety net incase we change that or there is
    /// somewhere this is used in API output.
    #[serde(rename = "LocallyRegisteredAsSidecar")]
    pub locally_registered_as_sidecar: bool,

    /// If not empty, PeerName represents the peer that the NodeService was imported from.
    #[serde(rename = "PeerName")]
    pub peer_name: String,

    #[serde(rename = "RaftIndex")]
    pub raft_index: RaftIndex,

}

/// PeeringServiceMeta is read-only information provided from an exported peer.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PeeringServiceMeta {
    #[serde(rename = "SNI")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sni: Option<String>,

    #[serde(rename = "SpiffeID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spiffe_id: Option<String>,

    #[serde(rename = "Protocol")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,

}

/// ServiceConnect are the shared Connect settings between all service
/// definitions from the agent to the state store.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ServiceConnect {
    /// Native is true when this service can natively understand Connect.
    #[serde(rename = "Native")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native: Option<bool>,

    /// SidecarService is a nested Service Definition to register at the same time.
    /// It's purely a convenience mechanism to allow specifying a sidecar service
    /// along with the application service definition. It's nested nature allows
    /// all of the fields to be defaulted which can reduce the amount of
    /// boilerplate needed to register a sidecar service separately, but the end
    /// result is identical to just making a second service registration via any
    /// other means.
    #[serde(rename = "SidecarService")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sidecar_service: Option<Box<ServiceDefinition>>,

    #[serde(rename = "PeerMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub peer_meta: Option<PeeringServiceMeta>,

}

/// HealthCheck represents a single check on a given node.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HealthCheck {
    #[serde(rename = "Node")]
    pub node: String,

    #[serde(rename = "CheckID")]
    pub check_id: String,

    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "Status")]
    pub status: String,

    #[serde(rename = "Notes")]
    pub notes: String,

    #[serde(rename = "Output")]
    pub output: String,

    #[serde(rename = "ServiceID")]
    pub service_id: String,

    #[serde(rename = "ServiceName")]
    pub service_name: String,

    #[serde(rename = "ServiceTags")]
    pub service_tags: String,

    #[serde(rename = "Type")]
    pub r#type: String,

    #[serde(rename = "Interval")]
    pub interval: String,

    #[serde(rename = "Timeout")]
    pub timeout: String,

    /// ExposedPort is the port of the exposed Envoy listener representing the
    /// HTTP or GRPC health check of the service.
    #[serde(rename = "ExposedPort")]
    pub exposed_port: isize,

    /// PeerName is the name of the peer the check was imported from.
    /// It is empty if the check was registered locally.
    #[serde(rename = "PeerName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub peer_name: Option<String>,

    #[serde(rename = "Definition")]
    pub definition: HealthCheckDefinition,

    #[serde(rename = "RaftIndex")]
    pub raft_index: RaftIndex,

}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HealthCheckDefinition {
    #[serde(rename = "HTTP")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub http: Option<String>,

    #[serde(rename = "TLSServerName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tls_server_name: Option<String>,

    #[serde(rename = "TLSSkipVerify")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tls_skip_verify: Option<bool>,

    #[serde(rename = "Header")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub header: Option<::std::collections::HashMap<String, String>>,

    #[serde(rename = "Method")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,

    #[serde(rename = "Body")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,

    #[serde(rename = "DisableRedirects")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disable_redirects: Option<bool>,

    #[serde(rename = "TCP")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tcp: Option<String>,

    #[serde(rename = "TCPUseTLS")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tcp_use_tls: Option<bool>,

    #[serde(rename = "UDP")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub udp: Option<String>,

    #[serde(rename = "H2PING")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub h2_ping: Option<String>,

    #[serde(rename = "OSService")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub os_service: Option<String>,

    #[serde(rename = "H2PingUseTLS")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub h2_ping_use_tls: Option<bool>,

}

/// Locality identifies where a given entity is running.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Locality {
    /// Region is region the zone belongs to.
    #[serde(rename = "Region")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,

    /// Zone is the zone the entity is running in.
    #[serde(rename = "Zone")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub zone: Option<String>,

}

