// Generated by 'scanner/main.go'.

use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLTokenPolicyLink {
    #[serde(rename = "ID")]
    pub id: String,

    #[serde(rename = "Name")]
    pub name: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLTokenRoleLink {
    #[serde(rename = "ID")]
    pub id: String,

    #[serde(rename = "Name")]
    pub name: String,
}

/// ACLServiceIdentity represents a high-level grant of all necessary privileges
/// to assume the identity of the named Service in the Catalog and within
/// Connect.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLServiceIdentity {
    #[serde(rename = "ServiceName")]
    pub service_name: String,

    /// Datacenters that the synthetic policy will be valid within.
    ///   - No wildcards allowed
    ///   - If empty then the synthetic policy is valid within all datacenters
    ///
    /// Only valid for global tokens. It is an error to specify this for local tokens.
    #[serde(rename = "Datacenters")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub datacenters: Option<String>,
}

pub type ACLServiceIdentities = Vec<ACLServiceIdentity>;

/// ACLNodeIdentity represents a high-level grant of all privileges
/// necessary to assume the identity of that node and manage it.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLNodeIdentity {
    /// NodeName identities the Node that this identity authorizes access to
    #[serde(rename = "NodeName")]
    pub node_name: String,

    /// Datacenter is required and specifies the datacenter of the node.
    #[serde(rename = "Datacenter")]
    pub datacenter: String,
}

pub type ACLNodeIdentities = Vec<ACLNodeIdentity>;

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLToken {
    /// This is the UUID used for tracking and management purposes
    #[serde(rename = "AccessorID")]
    pub accessor_id: String,

    /// This is the UUID used as the api token by clients
    #[serde(rename = "SecretID")]
    pub secret_id: String,

    /// Human readable string to display for the token (Optional)
    #[serde(rename = "Description")]
    pub description: String,

    /// List of policy links - nil/empty for legacy tokens or if service identities are in use.
    /// Note this is the list of IDs and not the names. Prior to token creation
    /// the list of policy names gets validated and the policy IDs get stored herein
    #[serde(rename = "Policies")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub policies: Option<ACLTokenPolicyLink>,

    /// List of role links. Note this is the list of IDs and not the names.
    /// Prior to token creation the list of role names gets validated and the
    /// role IDs get stored herein
    #[serde(rename = "Roles")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub roles: Option<ACLTokenRoleLink>,

    /// List of services to generate synthetic policies for.
    #[serde(rename = "ServiceIdentities")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_identities: Option<ACLServiceIdentities>,

    /// The node identities that this token should be allowed to manage.
    #[serde(rename = "NodeIdentities")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub node_identities: Option<ACLNodeIdentities>,

    /// The templated policies to generate synthetic policies for.
    #[serde(rename = "TemplatedPolicies")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub templated_policies: Option<ACLTemplatedPolicies>,

    /// Whether this token is DC local. This means that it will not be synced
    /// to the ACL datacenter and replicated to others.
    #[serde(rename = "Local")]
    pub local: bool,

    /// AuthMethod is the name of the auth method used to create this token.
    #[serde(rename = "AuthMethod")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auth_method: Option<String>,

    /// ACLAuthMethodEnterpriseMeta is the EnterpriseMeta for the AuthMethod that this token was created from
    #[serde(rename = "ACLAuthMethodEnterpriseMeta")]
    pub acl_auth_method_enterprise_meta: ACLAuthMethodEnterpriseMeta,
}

pub type ACLTokens = Vec<ACLToken>;

/// ACLReplicationStatus provides information about the health of the ACL
/// replication system.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLReplicationStatus {
    #[serde(rename = "Enabled")]
    pub enabled: bool,

    #[serde(rename = "Running")]
    pub running: bool,

    #[serde(rename = "SourceDatacenter")]
    pub source_datacenter: String,

    #[serde(rename = "ReplicationType")]
    pub replication_type: ACLReplicationType,

    #[serde(rename = "ReplicatedIndex")]
    pub replicated_index: u64,

    #[serde(rename = "ReplicatedRoleIndex")]
    pub replicated_role_index: u64,

    #[serde(rename = "ReplicatedTokenIndex")]
    pub replicated_token_index: u64,
}

/// ACLTokenGetRequest is used for token read operations at the RPC layer
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLTokenGetRequest {
    #[serde(rename = "TokenID")]
    pub token_id: String,

    #[serde(rename = "TokenIDType")]
    pub token_id_type: String,

    #[serde(rename = "Expanded")]
    pub expanded: bool,

    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

/// ACLTokenListRequest is used for token listing operations at the RPC layer
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLTokenListRequest {
    #[serde(rename = "IncludeLocal")]
    pub include_local: bool,

    #[serde(rename = "IncludeGlobal")]
    pub include_global: bool,

    #[serde(rename = "Policy")]
    pub policy: String,

    #[serde(rename = "Role")]
    pub role: String,

    #[serde(rename = "AuthMethod")]
    pub auth_method: String,

    #[serde(rename = "ServiceName")]
    pub service_name: String,

    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[serde(rename = "ACLAuthMethodEnterpriseMeta")]
    pub acl_auth_method_enterprise_meta: ACLAuthMethodEnterpriseMeta,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

/// ACLTokenListResponse is used to return the secret data free stubs
/// of the tokens
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLTokenListResponse {
    #[serde(rename = "Tokens")]
    pub tokens: ACLTokenListStubs,

    #[serde(rename = "QueryMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_meta: Option<QueryMeta>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLInitialTokenBootstrapRequest {
    #[serde(rename = "BootstrapSecret")]
    pub bootstrap_secret: String,

    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

/// ACLTokenResponse returns a single Token + metadata
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLTokenResponse {
    #[serde(rename = "Token")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token: Option<ACLToken>,

    #[serde(rename = "Redacted")]
    pub redacted: bool,

    #[serde(rename = "SourceDatacenter")]
    pub source_datacenter: String,

    #[serde(rename = "ExpandedTokenInfo")]
    pub expanded_token_info: ExpandedTokenInfo,

    #[serde(rename = "QueryMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_meta: Option<QueryMeta>,
}

/// ACLPolicyListRequest is used at the RPC layer to request a listing of policies
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLPolicyListRequest {
    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLPolicyListResponse {
    #[serde(rename = "Policies")]
    pub policies: ACLPolicyListStubs,

    #[serde(rename = "QueryMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_meta: Option<QueryMeta>,
}

/// ACLRoleListRequest is used at the RPC layer to request a listing of roles
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLRoleListRequest {
    #[serde(rename = "Policy")]
    pub policy: String,

    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLRoleListResponse {
    #[serde(rename = "Roles")]
    pub roles: ACLRoles,

    #[serde(rename = "QueryMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_meta: Option<QueryMeta>,
}

/// ACLBindingRuleListRequest is used at the RPC layer to request a listing of rules
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLBindingRuleListRequest {
    #[serde(rename = "AuthMethod")]
    pub auth_method: String,

    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLBindingRuleListResponse {
    #[serde(rename = "BindingRules")]
    pub binding_rules: ACLBindingRules,

    #[serde(rename = "QueryMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_meta: Option<QueryMeta>,
}

/// ACLAuthMethodListRequest is used at the RPC layer to request a listing of auth methods
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLAuthMethodListRequest {
    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLAuthMethodListResponse {
    #[serde(rename = "AuthMethods")]
    pub auth_methods: ACLAuthMethodListStubs,

    #[serde(rename = "QueryMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_meta: Option<QueryMeta>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLLoginParams {
    #[serde(rename = "AuthMethod")]
    pub auth_method: String,

    #[serde(rename = "BearerToken")]
    pub bearer_token: String,

    #[serde(rename = "Meta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meta: Option<::std::collections::HashMap<String, String>>,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLLoginRequest {
    #[serde(rename = "Auth")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auth: Option<ACLLoginParams>,

    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[serde(rename = "WriteRequest")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub write_request: Option<WriteRequest>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLLogoutRequest {
    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[serde(rename = "WriteRequest")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub write_request: Option<WriteRequest>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLAuthMethodEnterpriseMeta {}

/// ACLTemplatedPolicy represents a template used to generate a `synthetic` policy
/// given some input variables.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLTemplatedPolicy {
    /// TemplateID are hidden from all displays and should not be exposed to the users.
    #[serde(rename = "TemplateID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub template_id: Option<String>,

    /// TemplateName is used for display purposes mostly and should not be used for policy rendering.
    #[serde(rename = "TemplateName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub template_name: Option<String>,

    /// TemplateVariables are input variables required to render templated policies.
    #[serde(rename = "TemplateVariables")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub template_variables: Option<ACLTemplatedPolicyVariables>,

    /// Datacenters that the synthetic policy will be valid within.
    ///   - No wildcards allowed
    ///   - If empty then the synthetic policy is valid within all datacenters
    ///
    /// This is kept for legacy reasons to enable us to replace Node/Service Identities by templated policies.
    ///
    /// Only valid for global tokens. It is an error to specify this for local tokens.
    #[serde(rename = "Datacenters")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub datacenters: Option<String>,
}

pub type ACLTemplatedPolicies = Vec<ACLTemplatedPolicy>;

/// ACLTemplatedPolicyVariables are input variables required to render templated policies.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ACLTemplatedPolicyVariables {
    #[serde(rename = "Name")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// CheckDefinition is used to JSON decode the Check definitions
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CheckDefinition {
    #[serde(rename = "ID")]
    pub id: CheckID,

    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "Notes")]
    pub notes: String,

    #[serde(rename = "ServiceID")]
    pub service_id: String,

    #[serde(rename = "Token")]
    pub token: String,

    #[serde(rename = "Status")]
    pub status: String,

    /// Copied fields from CheckType without the fields
    /// already present in CheckDefinition:
    ///
    ///   ID (CheckID), Name, Status, Notes
    #[serde(rename = "ScriptArgs")]
    pub script_args: String,

    #[serde(rename = "HTTP")]
    pub http: String,

    #[serde(rename = "H2PING")]
    pub hRping: String,

    #[serde(rename = "H2PingUseTLS")]
    pub hR_ping_use_tls: bool,

    #[serde(rename = "Header")]
    pub header: ::std::collections::HashMap<String, String>,

    #[serde(rename = "Method")]
    pub method: String,

    #[serde(rename = "Body")]
    pub body: String,

    #[serde(rename = "DisableRedirects")]
    pub disable_redirects: bool,

    #[serde(rename = "TCP")]
    pub tcp: String,

    #[serde(rename = "TCPUseTLS")]
    pub tcp_use_tls: bool,

    #[serde(rename = "UDP")]
    pub udp: String,
}

/// ConnectAuthorizeRequest is the structure of a request to authorize
/// a connection.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConnectAuthorizeRequest {
    /// Target is the name of the service that is being requested.
    #[serde(rename = "Target")]
    pub target: String,

    /// EnterpriseMeta is the embedded Consul Enterprise specific metadata
    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    /// ClientCertURI is a unique identifier for the requesting client. This
    /// is currently the URI SAN from the TLS client certificate.
    ///
    /// ClientCertSerial is a colon-hex-encoded of the serial number for
    /// the requesting client cert. This is used to check against revocation
    /// lists.
    #[serde(rename = "ClientCertURI")]
    pub client_cert_uri: String,

    #[serde(rename = "ClientCertSerial")]
    pub client_cert_serial: String,
}

/// IndexedCARoots is the list of currently trusted CA Roots.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IndexedCARoots {
    /// ActiveRootID is the ID of a root in Roots that is the active CA root.
    /// Other roots are still valid if they're in the Roots list but are in
    /// the process of being rotated out.
    #[serde(rename = "ActiveRootID")]
    pub active_root_id: String,

    /// TrustDomain is the identification root for this Consul cluster. All
    /// certificates signed by the cluster's CA must have their identifying URI in
    /// this domain.
    ///
    /// This does not include the protocol (currently spiffe://) since we may
    /// implement other protocols in future with equivalent semantics. It should be
    /// compared against the "authority" section of a URI (i.e. host:port).
    ///
    /// We need to support migrating a cluster between trust domains to support
    /// Multi-DC migration in Enterprise. In this case the current trust domain is
    /// here but entries in Roots may also have ExternalTrustDomain set to a
    /// non-empty value implying they were previous roots that are still trusted
    /// but under a different trust domain.
    ///
    /// Note that we DON'T validate trust domain during AuthZ since it causes
    /// issues of loss of connectivity during migration between trust domains. The
    /// only time the additional validation adds value is where the cluster shares
    /// an external root (e.g. organization-wide root) with another distinct Consul
    /// cluster or PKI system. In this case, x509 Name Constraints can be added to
    /// enforce that Consul's CA can only validly sign or trust certs within the
    /// same trust-domain. Name constraints as enforced by TLS handshake also allow
    /// seamless rotation between trust domains thanks to cross-signing.
    #[serde(rename = "TrustDomain")]
    pub trust_domain: String,

    /// Roots is a list of root CA certs to trust.
    #[serde(rename = "Roots")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub roots: Option<CARoot>,

    /// QueryMeta contains the meta sent via a header. We ignore for JSON
    /// so this whole structure can be returned.
    #[serde(rename = "QueryMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_meta: Option<QueryMeta>,
}

/// ServiceDefinition is used to JSON decode the Service definitions. For
/// documentation on specific fields see NodeService which is better documented.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ServiceDefinition {
    #[serde(rename = "Kind")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<ServiceKind>,

    #[serde(rename = "ID")]
    pub id: String,

    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "Tags")]
    pub tags: String,

    #[serde(rename = "Address")]
    pub address: String,

    #[serde(rename = "TaggedAddresses")]
    pub tagged_addresses: ::std::collections::HashMap<String, ServiceAddress>,

    #[serde(rename = "Meta")]
    pub meta: ::std::collections::HashMap<String, String>,

    #[serde(rename = "Port")]
    pub port: isize,

    #[serde(rename = "SocketPath")]
    pub socket_path: String,

    #[serde(rename = "Check")]
    pub check: CheckType,

    #[serde(rename = "Checks")]
    pub checks: CheckTypes,

    #[serde(rename = "Weights")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weights: Option<Weights>,

    #[serde(rename = "Token")]
    pub token: String,

    #[serde(rename = "EnableTagOverride")]
    pub enable_tag_override: bool,

    #[serde(rename = "Locality")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locality: Option<Locality>,

    /// Proxy is the configuration set for Kind = connect-proxy. It is mandatory in
    /// that case and an error to be set for any other kind. This config is part of
    /// a proxy service definition. ProxyConfig may be a more natural name here, but
    /// it's confusing for the UX because one of the fields in ConnectProxyConfig is
    /// also called just "Config"
    #[serde(rename = "Proxy")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy: Option<ConnectProxyConfig>,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "Connect")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub connect: Option<ServiceConnect>,
}

/// QueryOptions is used to specify various flags for read queries
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct QueryOptions {
    /// Token is the ACL token ID. If not provided, the 'anonymous'
    /// token is assumed for backwards compatibility.
    #[serde(rename = "Token")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,

    /// If set, wait until query exceeds given index. Must be provided
    /// with MaxQueryTime.
    #[serde(rename = "MinQueryIndex")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_query_index: Option<u64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct WriteRequest {
    /// Token is the ACL token ID. If not provided, the 'anonymous'
    /// token is assumed for backwards compatibility.
    #[serde(rename = "Token")]
    pub token: String,
}

/// RegisterRequest is used for the Catalog.Register endpoint
/// to register a node as providing a service. If no service
/// is provided, the node is registered.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RegisterRequest {
    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[serde(rename = "ID")]
    pub id: NodeID,

    #[serde(rename = "Node")]
    pub node: String,

    #[serde(rename = "Address")]
    pub address: String,

    #[serde(rename = "TaggedAddresses")]
    pub tagged_addresses: ::std::collections::HashMap<String, String>,

    #[serde(rename = "NodeMeta")]
    pub node_meta: ::std::collections::HashMap<String, String>,

    #[serde(rename = "Service")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service: Option<NodeService>,

    #[serde(rename = "Check")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub check: Option<HealthCheck>,

    #[serde(rename = "Checks")]
    pub checks: HealthChecks,

    #[serde(rename = "Locality")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locality: Option<Locality>,

    /// SkipNodeUpdate can be used when a register request is intended for
    /// updating a service and/or checks, but doesn't want to overwrite any
    /// node information if the node is already registered. If the node
    /// doesn't exist, it will still be created, but if the node exists, any
    /// node portion of this update will not apply.
    #[serde(rename = "SkipNodeUpdate")]
    pub skip_node_update: bool,

    #[serde(rename = "PeerName")]
    pub peer_name: String,

    /// EnterpriseMeta is the embedded enterprise metadata
    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "WriteRequest")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub write_request: Option<WriteRequest>,

    #[serde(rename = "RaftIndex")]
    pub raft_index: RaftIndex,
}

/// DeregisterRequest is used for the Catalog.Deregister endpoint to
/// deregister a service, check, or node (only one should be provided).
/// If ServiceID or CheckID are not provided, the entire node is deregistered.
/// If a ServiceID is provided, any associated Checks with that service
/// are also deregistered.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeregisterRequest {
    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[serde(rename = "Node")]
    pub node: String,

    #[serde(rename = "ServiceID")]
    pub service_id: String,

    #[serde(rename = "CheckID")]
    pub check_id: CheckID,

    #[serde(rename = "PeerName")]
    pub peer_name: String,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "WriteRequest")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub write_request: Option<WriteRequest>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DatacentersRequest {
    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

/// DCSpecificRequest is used to query about a specific DC
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DCSpecificRequest {
    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[serde(rename = "NodeMetaFilters")]
    pub node_meta_filters: ::std::collections::HashMap<String, String>,

    #[serde(rename = "Source")]
    pub source: QuerySource,

    #[serde(rename = "PeerName")]
    pub peer_name: String,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

/// ServiceSpecificRequest is used to query about a specific service
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ServiceSpecificRequest {
    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    /// The name of the peer that the requested service was imported from.
    #[serde(rename = "PeerName")]
    pub peer_name: String,

    /// The name of the sameness group that should be the target of the query.
    #[serde(rename = "SamenessGroup")]
    pub sameness_group: String,

    #[serde(rename = "NodeMetaFilters")]
    pub node_meta_filters: ::std::collections::HashMap<String, String>,

    #[serde(rename = "ServiceName")]
    pub service_name: String,

    #[serde(rename = "ServiceKind")]
    pub service_kind: ServiceKind,

    /// DEPRECATED (singular-service-tag) - remove this when backwards RPC compat
    /// with 1.2.x is not required.
    #[serde(rename = "ServiceTag")]
    pub service_tag: String,

    #[serde(rename = "ServiceTags")]
    pub service_tags: String,

    #[serde(rename = "ServiceAddress")]
    pub service_address: String,

    #[serde(rename = "TagFilter")]
    pub tag_filter: bool,

    #[serde(rename = "HealthFilterType")]
    pub health_filter_type: HealthFilterType,

    #[serde(rename = "Source")]
    pub source: QuerySource,

    /// Connect if true will only search for Connect-compatible services.
    #[serde(rename = "Connect")]
    pub connect: bool,

    /// Ingress if true will only search for Ingress gateways for the given service.
    #[serde(rename = "Ingress")]
    pub ingress: bool,

    /// MergeCentralConfig when set to true returns a service definition merged with
    /// the proxy-defaults/global and service-defaults/:service config entries.
    /// This can be used to ensure a full service definition is returned in the response
    /// especially when the service might not be written into the catalog that way.
    #[serde(rename = "MergeCentralConfig")]
    pub merge_central_config: bool,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

/// NodeSpecificRequest is used to request the information about a single node
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NodeSpecificRequest {
    #[serde(rename = "Datacenter")]
    pub datacenter: String,

    #[serde(rename = "Node")]
    pub node: String,

    #[serde(rename = "PeerName")]
    pub peer_name: String,

    /// MergeCentralConfig when set to true returns a service definition merged with
    /// the proxy-defaults/global and service-defaults/:service config entries.
    /// This can be used to ensure a full service definition is returned in the response
    /// especially when the service might not be written into the catalog that way.
    #[serde(rename = "MergeCentralConfig")]
    pub merge_central_config: bool,

    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "QueryOptions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_options: Option<QueryOptions>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IndexedNodes {
    #[serde(rename = "Nodes")]
    pub nodes: Nodes,

    #[serde(rename = "QueryMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_meta: Option<QueryMeta>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IndexedServices {
    #[serde(rename = "Services")]
    pub services: Services,

    /// In various situations we need to know the meta that the services are for - in particular
    /// this is needed to be able to properly filter the list based on ACLs
    #[cfg(feature = "enterprise")]
    #[serde(rename = "EnterpriseMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enterprise_meta: Option<EnterpriseMeta>,

    #[serde(rename = "QueryMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_meta: Option<QueryMeta>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IndexedNodeServices {
    /// TODO: This should not be a pointer, see comments in
    /// agent/catalog_endpoint.go.
    #[serde(rename = "NodeServices")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub node_services: Option<NodeServices>,

    #[serde(rename = "QueryMeta")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_meta: Option<QueryMeta>,
}
